// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBups7ALqKyGiHMFrJ2nS46y-O9TP440EE',
    appId: '1:97890621500:web:613890247c2c919f1fcb39',
    messagingSenderId: '97890621500',
    projectId: 'royal-riders-d205b',
    authDomain: 'royal-riders-d205b.firebaseapp.com',
    storageBucket: 'royal-riders-d205b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvHyiIcAilXPhTeuCYxNG_YoiT6accDBU',
    appId: '1:97890621500:android:138017978934118e1fcb39',
    messagingSenderId: '97890621500',
    projectId: 'royal-riders-d205b',
    storageBucket: 'royal-riders-d205b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzxqFgIpMhq51YkoMqzGlgVAIGKmjY2oU',
    appId: '1:97890621500:ios:3c9f9b882e98ede61fcb39',
    messagingSenderId: '97890621500',
    projectId: 'royal-riders-d205b',
    storageBucket: 'royal-riders-d205b.appspot.com',
    iosClientId: '97890621500-fk3q9qhsuidg763ujub76a3vjeorhh2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainTracking',
  );
}
